## Imports
---

In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
from datacleaner import DataCleaner

DATA_DIR = Path("../data/raw")

## Data
---

In [2]:
df_ventas = pd.read_csv(DATA_DIR / "ventas.csv")
cleaner_ventas = DataCleaner(df_ventas)
cleaner_ventas.df.set_index("id_venta", inplace=True)

df_clientes = pd.read_csv(DATA_DIR / "clientes.csv")
cleaner_clientes = DataCleaner(df_clientes)
cleaner_clientes.df.set_index("id_cliente", inplace=True)

df_marketing = pd.read_csv(DATA_DIR / "marketing.csv")
cleaner_marketing = DataCleaner(df_marketing)
cleaner_marketing.df.set_index("id_campanha", inplace=True)

## 'Ventas'
---

In [3]:
cleaner_ventas.get_summary(name="df_ventas")

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  📋  df_ventas
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Filas               3,035
  Columnas            5
  Nulos totales       4
  Duplicados          35

──────────────────────────────────────────────────────────────────────
  Columna                   Tipo           Únicos    Nulos    % nulos
──────────────────────────────────────────────────────────────────────
  producto                  str                30        0      0.00%
  precio                    str             2,590        2      0.07% ⚠️
  cantidad                  float64            12        2      0.07% ⚠️
  fecha_venta               str               364        0      0.00%
  categoria                 str                 3        0      0.00%

────────────────────────────────────────────────────────────
  Filas duplicadas: 35 ⚠️

────────────────────────────────────────────────────────────
  Primeras 5 filas:

                   producto   precio  cantidad fecha_venta          categoria
id_venta
792       Cuadro decorativo   $69.94       5.0  02/01/2024         Decoración
811         Lámpara de mesa  $105.10       5.0  02/01/2024         Decoración
1156               Secadora   $97.96       3.0  02/01/2024  Electrodomésticos
1372               Heladera  $114.35       8.0  02/01/2024  Electrodomésticos
1546               Secadora  $106.21       4.0  02/01/2024  Electrodomésticos

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

### Datos nulos

In [4]:
cleaner_ventas.clean_nulls(columns=["precio", "cantidad"], delete=True)

Datos nulos correctamente eliminados

### Datos duplicados

In [5]:
cleaner_ventas.clean_dups_by_id()

Filas completamente duplicadas: 70
Filas con index duplicado: 70
¿Coinciden? True
 --------------------------------------------------------------------------------
Filas restantes: 2998
Index duplicados restantes: 0

### Corrección de tipos de datos

In [6]:
cleaner_ventas.cast_columns(columns=["precio"], to="float64")
cleaner_ventas.cast_columns(columns=["cantidad"], to="int64")
cleaner_ventas.cast_columns(columns=["fecha_venta"], to="datetime")

✓ 'precio' convertida correctamente → float64
✓ 'cantidad' convertida correctamente → int64
✓ 'fecha_venta' convertida correctamente → datetime64[us]

### Outliers

In [7]:
cleaner_ventas.display_outliers(columns=["precio", "cantidad"], method="iqr")

✅ No se detectaron outliers en las columnas.

## 'Marketing'
---

In [8]:
cleaner_marketing.get_summary(name="df_marketing")

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  📋  df_marketing
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Filas               90
  Columnas            5
  Nulos totales       0
  Duplicados          0

──────────────────────────────────────────────────────────────────────
  Columna                   Tipo           Únicos    Nulos    % nulos
──────────────────────────────────────────────────────────────────────
  producto                  str                30        0      0.00%
  canal                     str                 3        0      0.00%
  costo                     float64            81        0      0.00%
  fecha_inicio              str                78        0      0.00%
  fecha_fin                 str                78        0      0.00%

────────────────────────────────────────────────────────────
  Filas duplicadas: 0 ✅

────────────────────────────────────────────────────────────
  Primeras 5 filas:

                    producto  canal  costo fecha_inicio   fecha_fin
id_campanha
74           Adorno de pared     TV   4.81   20/03/2024  03/05/2024
12                    Tablet   RRSS   3.40   26/03/2024  13/05/2024
32           Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
21                Smartphone   RRSS   6.37   29/03/2024  16/05/2024
58                  Alfombra  Email   4.25   31/03/2024  05/05/2024

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

### Corrección de tipos de datos

In [9]:
cleaner_marketing.cast_columns(columns=["fecha_inicio", "fecha_fin"], to="datetime")

✓ 'fecha_inicio' convertida correctamente → datetime64[us]
✓ 'fecha_fin' convertida correctamente → datetime64[us]

### Outliers

En este caso no se eliminará ni reemplazará el outlier detectado, ya que es perfectamente normal dado el contexto, y no es un caso extremo.

In [10]:
cleaner_marketing.display_outliers(columns=["costo"], method="iqr")

             producto canal  costo fecha_inicio  fecha_fin
id_campanha
88           Alfombra    TV   7.39   2024-07-25 2024-08-31

## 'Clientes'
---

In [11]:
cleaner_clientes.get_summary(name="df_clientes")

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  📋  df_clientes
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Filas               567
  Columnas            4
  Nulos totales       0
  Duplicados          0

──────────────────────────────────────────────────────────────────────
  Columna                   Tipo           Únicos    Nulos    % nulos
──────────────────────────────────────────────────────────────────────
  nombre                    str               567        0      0.00%
  edad                      int64              49        0      0.00%
  ciudad                    str                12        0      0.00%
  ingresos                  float64           547        0      0.00%

────────────────────────────────────────────────────────────
  Filas duplicadas: 0 ✅

────────────────────────────────────────────────────────────
  Primeras 5 filas:

                         nombre  edad         ciudad  ingresos
id_cliente
1               Aloysia Screase    44  Mar del Plata  42294.68
2           Kristina Scaplehorn    25        Posadas  24735.04
3                Filip Castagne    50    Resistencia  35744.85
4                   Liuka Luard    39   Bahía Blanca  27647.96
5                 Dore Cockshtt    28        Rosario  28245.65

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

### Corrección de tipos de datos

In [12]:
cleaner_clientes.cast_columns(columns=["ciudad"], to="category")

✓ 'ciudad' convertida correctamente → category

### Outliers

Valores atípicos en `ingresos`: Solamente se tratarán los outliers bajos, ya que teniendo en cuenta que se trata de ciudades en Argentina, esos valores bajos en ingresos no son realistas teniendo en cuenta el salario mínimo.

Los outliers altos se dejarán como están, porque aunque sean casos muy raros o excepcionales, son perfectamente posibles.

In [13]:
cleaner_clientes.display_outliers(columns=["ingresos"], method="iqr")

                      nombre  edad         ciudad  ingresos
id_cliente
91            Reynold Aspray    38          Merlo    170.29
158         Electra Shilston    35        Posadas    786.77
172              Bent Isenor    28       Santa Fe  74147.65
289            Rene Knowlden    40          Merlo    227.66
329         Jarid Davidovici    36    Resistencia  88053.01
457         Brigitta Reddoch    53  Mar del Plata  71570.89

In [14]:
cleaner_clientes.clean_outliers(columns=["ingresos"], method="iqr", side="lower")

  Método: IQR  |  Acción: cappeados  |  Lado: solo bajos

  Columna                  Bajos   Altos   Tratados  Sin tocar   Límite inf.   Límite sup.
  ──────────────────────────────────────────────────────────────────────────────────────
  ingresos                     3       3         3 ⚠️         3       1352.45     67119.89
  ──────────────────────────────────────────────────────────────────────────────────────
  TOTAL                           3 tratados  |       3 sin tocar

## Guardar datos limpios en `root/data/clean`
---

Formato `parquet` para mantener los tipos de datos.

In [15]:
CLEAN_DATA_DIR = Path("../data/clean")

cleaner_ventas.df.reset_index(inplace=True)
cleaner_ventas.df.to_parquet(CLEAN_DATA_DIR / "ventas.parquet", index=False)

cleaner_marketing.df.reset_index(inplace=True)
cleaner_marketing.df.to_parquet(CLEAN_DATA_DIR / "marketing.parquet", index=False)

cleaner_clientes.df.reset_index(inplace=True)
cleaner_clientes.df.to_parquet(CLEAN_DATA_DIR / "clientes.parquet", index=False)